#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720
#define SPEED 5
#define BOOSTSPEED 20
#define SLOWMOTION 2
#define BGMAPX 5760 
#define BGMAPY 720
#define GAME_VERSION 0.2.0
#define GAME_NAME CYBERBITGAME
#define TILE_SIZE 100

#endif
